# Builder #
FROM rust:1.90 AS builder

WORKDIR /app

COPY . .

RUN cargo build --release -p api-service

# Runtime #
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 10001 appuser

WORKDIR /app

COPY --from=builder \
    /app/target/release/api-service \
    /usr/local/bin/api-service

USER appuser

EXPOSE 3000

CMD ["api-service"]